import archiver from 'archiver';

export async function handleExportZip(req, res) {
  try {
    const { code, framework = 'react-tailwind', name = 'generated-ui' } = req.body;

    if (!code) {
      return res.status(400).json({ error: 'Code is required for ZIP export.' });
    }

    const safeName = name.toLowerCase().replace(/[^a-z0-9_-]/g, '_');

    res.attachment(`${safeName}.zip`);
    res.setHeader('Content-Type', 'application/zip');

    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => {
      console.error('[Archiver Error]:', err);
      res.status(500).send({ error: err.message });
    });

    archive.pipe(res);

    if (framework === 'react-tailwind') {
      // 1. package.json
      archive.append(
        JSON.stringify(
          {
            name: safeName,
            private: true,
            version: '0.0.0',
            type: 'module',
            scripts: {
              dev: 'vite',
              build: 'vite build',
              preview: 'vite preview',
            },
            dependencies: {
              react: '^18.3.1',
              'react-dom': '^18.3.1',
              'lucide-react': '^0.475.0',
            },
            devDependencies: {
              '@types/react': '^18.3.3',
              '@types/react-dom': '^18.3.0',
              '@vitejs/plugin-react': '^4.3.1',
              autoprefixer: '^10.4.19',
              postcss: '^8.4.38',
              tailwindcss: '^3.4.4',
              vite: '^5.3.1',
            },
          },
          null,
          2
        ),
        { name: 'package.json' }
      );

      // 2. vite.config.js
      archive.append(
        `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
        { name: 'vite.config.js' }
      );

      // 3. tailwind.config.js
      archive.append(
        `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
        { name: 'tailwind.config.js' }
      );

      // 4. postcss.config.js
      archive.append(
        `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,
        { name: 'postcss.config.js' }
      );

      // 5. index.html
      archive.append(
        `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
        { name: 'index.html' }
      );

      // 6. src/index.css
      archive.append(
        `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  background-color: #09090b;
  color: #f4f4f5;
}
`,
        { name: 'src/index.css' }
      );

      // 7. src/main.jsx
      archive.append(
        `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,
        { name: 'src/main.jsx' }
      );

      // 8. src/App.jsx (the generated code)
      archive.append(code, { name: 'src/App.jsx' });

      // 9. README.md
      archive.append(
        `# ${name}

Generated by Screenshot-to-Code AI.

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run development server:
   \`\`\`bash
   npm run dev
   \`\`\`
`,
        { name: 'README.md' }
      );
    } else {
      // HTML + CSS Export
      archive.append(code, { name: 'index.html' });
      archive.append(
        `# ${name}

Generated by Screenshot-to-Code AI.

Open \`index.html\` directly in any browser.
`,
        { name: 'README.md' }
      );
    }

    await archive.finalize();
  } catch (error) {
    console.error('[Export Zip Controller Error]:', error);
    if (!res.headersSent) {
      return res.status(500).json({ error: error.message || 'Failed to export project ZIP.' });
    }
  }
}
